$ErrorActionPreference = "Stop"

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -notmatch $Pattern) {
        throw $Message
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -match $Pattern) {
        throw $Message
    }
}

Assert-Contains -Path "app.py" -Pattern 'settings\.json' -Message "app.py must persist settings to settings.json"
Assert-Contains -Path "app.py" -Pattern 'find_available_port' -Message "app.py must avoid stale services by selecting an available port"
Assert-Contains -Path "app.py" -Pattern 'startup_enabled' -Message "app.py must define startup_enabled"
Assert-Contains -Path "app.py" -Pattern 'floating_price_enabled' -Message "app.py must support a desktop floating price setting"
Assert-Contains -Path "app.py" -Pattern 'floating_price_position_saved' -Message "app.py must ignore stale floating price coordinates without a saved-position marker"
Assert-Contains -Path "app.py" -Pattern 'floating_price_x' -Message "app.py must persist the floating price x coordinate"
Assert-Contains -Path "app.py" -Pattern 'floating_price_y' -Message "app.py must persist the floating price y coordinate"
Assert-Contains -Path "app.py" -Pattern 'floating_price_opacity' -Message "floating price settings must support opacity"
Assert-Contains -Path "app.py" -Pattern 'floating_price_display_mode' -Message "floating price settings must support display modes"
Assert-Contains -Path "app.py" -Pattern 'floating_price_preset' -Message "floating price settings must support size presets"
Assert-Contains -Path "app.py" -Pattern 'VALID_FLOATING_PRESETS' -Message "floating price presets must be validated"
Assert-Contains -Path "app.py" -Pattern 'floating_price_snap_edge' -Message "floating price settings must support edge snapping"
Assert-Contains -Path "app.py" -Pattern 'GoldMonitorFloatingPriceWindow' -Message "app.py must create a native floating price window"
Assert-Contains -Path "app.py" -Pattern 'update_floating_price' -Message "price refreshes must update the floating price window"
Assert-Contains -Path "app.py" -Pattern 'WM_LBUTTONDOWN' -Message "floating price window must handle drag start"
Assert-Contains -Path "app.py" -Pattern 'WM_LBUTTONDBLCLK' -Message "floating price window must open the main window on double click"
Assert-Contains -Path "app.py" -Pattern 'CS_DBLCLKS' -Message "floating price window class must opt in to double-click messages"
Assert-Contains -Path "app.py" -Pattern 'WM_MOUSEMOVE' -Message "floating price window must handle dragging"
Assert-Contains -Path "app.py" -Pattern 'WM_RBUTTONUP' -Message "floating price window must handle right-click menus"
Assert-Contains -Path "app.py" -Pattern 'WM_CONTEXTMENU' -Message "floating price window must handle context menu messages"
Assert-Contains -Path "app.py" -Pattern 'TrackPopupMenu' -Message "floating price window must show a native context menu"
Assert-Contains -Path "app.py" -Pattern 'FLOATING_MENU_RISK' -Message "floating price context menu must expose risk analysis"
Assert-Contains -Path "app.py" -Pattern '_floating_status_text' -Message "floating price window must show update time and source status"
Assert-Contains -Path "app.py" -Pattern '_floating_trend_state' -Message "floating price window must color price by trend"
Assert-Contains -Path "app.py" -Pattern 'global _floating_drag_state' -Message "floating price drag state must be shared across Win32 mouse messages"
Assert-Contains -Path "app.py" -Pattern '_save_floating_position' -Message "floating price window must persist dragged position"
Assert-Contains -Path "app.py" -Pattern '_floating_positioned' -Message "floating price refreshes must not force repositioning after initial placement"
Assert-Contains -Path "app.py" -Pattern '_refresh_price_from_tray_menu' -Message "tray menu must support manual price refresh"
Assert-Contains -Path "app.py" -Pattern '_open_risk_analysis_from_tray_menu' -Message "tray menu must support risk analysis"
Assert-Contains -Path "app.py" -Pattern '_toggle_floating_price_from_tray_menu' -Message "tray menu must support floating price toggle"
Assert-Contains -Path "app.py" -Pattern '刷新行情' -Message "tray menu must render a refresh action"
Assert-Contains -Path "app.py" -Pattern '风险分析' -Message "tray menu must render a risk analysis action"
Assert-Contains -Path "app.py" -Pattern '切换悬浮条' -Message "tray menu must render a floating price toggle action"
Assert-Contains -Path "app.py" -Pattern 'Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Message "app.py must manage HKCU Run startup"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_settings"\)' -Message "app.py must expose get_settings socket event"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("update_settings"\)' -Message "app.py must expose update_settings socket event"
Assert-Contains -Path "app.py" -Pattern '--startup' -Message "app.py must support --startup"
Assert-Contains -Path "app.py" -Pattern 'REQUEST_TIMEOUT' -Message "app.py must use a short network request timeout"
Assert-NotContains -Path "app.py" -Pattern 'cors_allowed_origins\s*=\s*"\*"' -Message "Socket.IO must not allow every browser origin"
Assert-Contains -Path "app.py" -Pattern 'SOCKET_ACCESS_TOKEN' -Message "Socket.IO clients must use a per-process access token"
Assert-Contains -Path "templates\index.html" -Pattern 'auth:\s*\{\s*token:\s*SOCKET_ACCESS_TOKEN\s*\}' -Message "frontend must send the Socket.IO access token"
Assert-Contains -Path "app.py" -Pattern 'APP_USER_MODEL_ID\s*=\s*"GoldMonitor\.App"' -Message "app.py must define the Windows AppUserModelID"
Assert-Contains -Path "app.py" -Pattern 'app_id=APP_USER_MODEL_ID' -Message "desktop toast must use the application AppUserModelID"
Assert-Contains -Path "app.py" -Pattern 'icon=notification_icon' -Message "desktop toast must include the app icon"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("close_choice"\)' -Message "app.py must receive close choices from the frontend"
Assert-Contains -Path "app.py" -Pattern 'socketio\.emit\("show_close_dialog"' -Message "app.py must ask the frontend to show close confirmation"
Assert-Contains -Path "app.py" -Pattern 'hide_main_window' -Message "app.py must hide the pywebview window to tray"
Assert-Contains -Path "app.py" -Pattern 'SW_HIDE' -Message "app.py must use a Win32 hide fallback for tray minimization"
Assert-NotContains -Path "app.py" -Pattern 'import tkinter' -Message "app.py must not depend on tkinter in packaged runtime"
Assert-Contains -Path "app.py" -Pattern 'show_alert_dialog' -Message "app.py must show system alert dialog"
Assert-Contains -Path "templates\index.html" -Pattern 'openSettings' -Message "index.html must expose a settings entry"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabGeneral' -Message "settings dialog must expose a general settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'setFloatingPrice' -Message "settings dialog must expose a floating price toggle"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabEmail' -Message "settings dialog must expose an email settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'switchSettingsTab' -Message "settings dialog must support switching sections"
Assert-Contains -Path "templates\index.html" -Pattern 'settings-body \{[^}]*overflow-y:auto' -Message "settings dialog body must support scrolling"
Assert-Contains -Path "templates\index.html" -Pattern 'settings-foot \{[^}]*flex:0 0 auto' -Message "settings dialog actions must remain fixed outside the scroll body"
Assert-Contains -Path "templates\index.html" -Pattern 'update_settings' -Message "index.html must save settings"
Assert-Contains -Path "templates\index.html" -Pattern 'id="closeBackdrop"' -Message "index.html must contain an app close confirmation dialog"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''show_close_dialog''' -Message "index.html must handle backend close confirmation requests"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''close_choice''' -Message "index.html must send close choices to the backend"
Assert-Contains -Path "templates\index.html" -Pattern 'id="alertBackdrop"' -Message "index.html must contain an app alert dialog"
Assert-Contains -Path "templates\index.html" -Pattern 'showAlertModal' -Message "index.html must show app alert dialogs from alert events"
Assert-Contains -Path "templates\index.html" -Pattern 'max-width:none' -Message "layout must use the available window width"
Assert-Contains -Path "templates\index.html" -Pattern 'grid-template-columns:minmax\(0, 1fr\) var\(--right-width\)' -Message "layout must use responsive grid columns"
Assert-Contains -Path "templates\index.html" -Pattern '@media \(max-width:1100px\)' -Message "layout must switch at medium widths"
Assert-Contains -Path "templates\index.html" -Pattern 'height:100vh' -Message "layout must lock the app to one viewport"
Assert-Contains -Path "templates\index.html" -Pattern 'overflow:hidden' -Message "layout must avoid page-level scrolling"
Assert-Contains -Path "templates\index.html" -Pattern 'openUpdate' -Message "index.html must expose an update entry"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''check_update''' -Message "index.html must request update checks"
Assert-Contains -Path "templates\index.html" -Pattern 'AUTO_UPDATE_CHECK_INTERVAL_MS' -Message "index.html must define automatic update check interval"
Assert-Contains -Path "templates\index.html" -Pattern 'scheduleAutoUpdateCheck' -Message "index.html must schedule automatic update checks"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''install_update''' -Message "index.html must request update install"
Assert-Contains -Path "templates\index.html" -Pattern 'updateProgress' -Message "update dialog must show download progress"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''install_update'',\s*pendingUpdateInfo\)' -Message "frontend must not send installer URLs back to install_update"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''update_status''' -Message "index.html must handle update status"
Assert-Contains -Path "app.py" -Pattern 'APP_VERSION' -Message "app.py must expose a current app version"
Assert-Contains -Path "app.py" -Pattern 'DEFAULT_UPDATE_MANIFEST_URL' -Message "app.py must define a default update source URL in code"
Assert-Contains -Path "app.py" -Pattern 'update_manifest_url' -Message "settings must support an update manifest url"
Assert-Contains -Path "app.py" -Pattern 'compare_versions' -Message "app.py must compare update versions"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("check_update"\)' -Message "app.py must expose check_update socket event"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("install_update"\)' -Message "app.py must expose install_update socket event"
Assert-Contains -Path "app.py" -Pattern 'progress_callback' -Message "updater must report installer download progress"
Assert-Contains -Path "app.py" -Pattern 'GoldMonitorSetup' -Message "updater must download the setup executable"
Assert-Contains -Path ".github\workflows\release.yml" -Pattern 'GoldMonitor-macOS\.dmg' -Message "release workflow must publish the macOS DMG"
Assert-Contains -Path "scripts\build_macos_dmg.sh" -Pattern 'hdiutil create' -Message "macOS packaging must create a DMG"
Assert-Contains -Path "scripts\generate_release_manifest.py" -Pattern 'CHANGELOG\.md' -Message "release metadata must read version notes from CHANGELOG.md"
Assert-Contains -Path "scripts\generate_release_manifest.py" -Pattern 'missing release notes' -Message "release metadata must fail when release notes are missing"
Assert-Contains -Path "CHANGELOG.md" -Pattern '## 1\.3\.2' -Message "CHANGELOG.md must document the current release"
Assert-Contains -Path "app.py" -Pattern 'NEWS_CACHE_PATH' -Message "app.py must cache gold-related news locally"
Assert-Contains -Path "app.py" -Pattern 'THRESHOLDS_PATH' -Message "app.py must persist thresholds locally"
Assert-Contains -Path "app.py" -Pattern 'load_thresholds' -Message "app.py must load thresholds from disk"
Assert-Contains -Path "app.py" -Pattern 'save_thresholds' -Message "app.py must save thresholds to disk"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("refresh_price"\)' -Message "app.py must expose manual price refresh"
Assert-Contains -Path "app.py" -Pattern 'last_fetch_error' -Message "app.py must track fetch failure reasons"
Assert-Contains -Path "app.py" -Pattern 'fetch_status' -Message "app.py must expose fetch status"
Assert-Contains -Path "app.py" -Pattern 'source_health' -Message "app.py must track data source health"
Assert-Contains -Path "app.py" -Pattern 'record_source_health' -Message "app.py must record source health metrics"
Assert-Contains -Path "app.py" -Pattern 'source_price_samples' -Message "app.py must keep source price samples for comparison"
Assert-Contains -Path "app.py" -Pattern 'build_source_comparison_state' -Message "app.py must build data source comparison state"
Assert-Contains -Path "app.py" -Pattern 'refresh_source_comparison' -Message "price refresh must update data source comparison"
Assert-Contains -Path "app.py" -Pattern 'SOURCE_COMPARISON_ANOMALY_PCT' -Message "source comparison must define an anomaly threshold"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_source_health"\)' -Message "app.py must expose source health lookup"
Assert-Contains -Path "templates\index.html" -Pattern 'sourceHealth' -Message "frontend must render source health"
Assert-Contains -Path "templates\index.html" -Pattern 'sourceComparison' -Message "frontend must render source price comparison"
Assert-Contains -Path "templates\index.html" -Pattern 'renderSourceComparison' -Message "frontend must update source price comparison"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''get_source_health''' -Message "frontend must request source health"
Assert-Contains -Path "app.py" -Pattern 'MARKET_CACHE_PATH' -Message "app.py must cache market rates locally"
Assert-Contains -Path "app.py" -Pattern 'SINA_GOLD_URL' -Message "app.py must include Sina gold source"
Assert-Contains -Path "app.py" -Pattern 'parse_sina_gold' -Message "app.py must parse Sina gold data"
Assert-Contains -Path "app.py" -Pattern 'save_xauusd_cache' -Message "app.py must cache successful XAU/USD prices locally"
Assert-Contains -Path "app.py" -Pattern 'load_valid_xauusd_cache' -Message "app.py must reuse fresh cached XAU/USD prices when live sources fail"
Assert-Contains -Path "app.py" -Pattern 'fetch_usdcny_rate_result' -Message "app.py must fetch USD/CNY from multiple sources"
Assert-Contains -Path "app.py" -Pattern 'parse_sina_forex' -Message "app.py must parse Sina USD/CNY rates"
Assert-Contains -Path "app.py" -Pattern 'parse_frankfurter_forex' -Message "app.py must parse Frankfurter USD/CNY rates"
Assert-Contains -Path "app.py" -Pattern 'rate_cached' -Message "price updates must expose cached rate status"
Assert-Contains -Path "app.py" -Pattern 'GDELT' -Message "app.py must include a public gold news source"
Assert-Contains -Path "app.py" -Pattern 'press_all\.xml' -Message "app.py must include the Federal Reserve RSS feed"
Assert-Contains -Path "app.py" -Pattern 'bls_latest\.rss' -Message "app.py must include the BLS RSS feed"
Assert-Contains -Path "app.py" -Pattern 'def fetch_gold_news' -Message "app.py must fetch gold-related news"
Assert-Contains -Path "app.py" -Pattern 'def start_news_fetching' -Message "app.py must refresh news in the background"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_news"\)' -Message "app.py must expose get_news socket event"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("refresh_news"\)' -Message "app.py must expose refresh_news socket event"
Assert-Contains -Path "app.py" -Pattern 'news_updated' -Message "app.py must emit news updates to the frontend"
Assert-Contains -Path "app.py" -Pattern 'related_news' -Message "alerts must include related news candidates"
Assert-NotContains -Path "templates\index.html" -Pattern 'newsButton' -Message "index.html must not expose a gold news toolbar entry"
Assert-NotContains -Path "templates\index.html" -Pattern 'id="newsBackdrop"' -Message "index.html must not expose the gold news panel"
Assert-NotContains -Path "templates\index.html" -Pattern 'openNews' -Message "index.html must not expose a gold news entry"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''get_news''' -Message "index.html must not request manual news panel data"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''refresh_news''' -Message "index.html must not request manual news refresh"
Assert-Contains -Path "templates\index.html" -Pattern 'related-news' -Message "alert dialog must render related news"
Assert-Contains -Path "app.py" -Pattern 'risk_assistant_enabled' -Message "settings must support a risk assistant toggle"
Assert-Contains -Path "app.py" -Pattern 'risk_assistant_depth' -Message "risk assistant must support analysis depth"
Assert-Contains -Path "app.py" -Pattern 'deepseek_base_url' -Message "settings must support a DeepSeek API base url"
Assert-Contains -Path "app.py" -Pattern 'deepseek_model' -Message "settings must support a DeepSeek model"
Assert-Contains -Path "app.py" -Pattern 'deepseek_api_key' -Message "settings must persist the DeepSeek API key locally"
Assert-Contains -Path "app.py" -Pattern 'public_settings_snapshot' -Message "backend must expose a sanitized public settings snapshot"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("request_risk_analysis"\)' -Message "backend must expose a manual risk analysis socket event"
Assert-Contains -Path "app.py" -Pattern 'build_risk_analysis_context' -Message "backend must build a read-only risk analysis context"
Assert-Contains -Path "app.py" -Pattern 'call_deepseek_risk_analysis' -Message "backend must call DeepSeek for risk analysis"
Assert-Contains -Path "app.py" -Pattern 'risk_scorecard' -Message "risk assistant context must include a scorecard"
Assert-Contains -Path "app.py" -Pattern 'data_quality' -Message "risk assistant context must include data quality"
Assert-Contains -Path "app.py" -Pattern 'multi_period_trends' -Message "risk assistant context must include multiple trend periods"
Assert-Contains -Path "app.py" -Pattern 'openai_compatible' -Message "risk assistant must keep an OpenAI-compatible provider extension point"
Assert-Contains -Path "app.py" -Pattern 'openai_compatible_api_key_masked' -Message "compatible provider API keys must be masked before reaching the frontend"
Assert-Contains -Path "app.py" -Pattern 'risk_assistant_max_tokens' -Message "risk assistant must expose a max-token cost control"
Assert-Contains -Path "app.py" -Pattern 'risk_assistant_cooldown_seconds' -Message "risk assistant must expose a repeated-click cooldown"
Assert-Contains -Path "app.py" -Pattern 'risk_assistant_cache_minutes' -Message "risk assistant must expose a repeated-analysis cache window"
Assert-Contains -Path "app.py" -Pattern 'risk_analysis_history' -Message "risk assistant must keep bounded local analysis history"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_risk_model_options"\)' -Message "backend must expose model option lookup"
Assert-Contains -Path "app.py" -Pattern 'risk_model_options_updated' -Message "backend must emit model option lookup results"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("test_risk_model"\)' -Message "backend must expose model availability diagnostics"
Assert-Contains -Path "app.py" -Pattern 'risk_model_test_result' -Message "backend must emit model diagnostic results"
Assert-Contains -Path "app.py" -Pattern 'risk_analysis_cache_hit' -Message "backend must emit repeated-analysis cache hits"
Assert-Contains -Path "app.py" -Pattern 'parse_risk_analysis_sections' -Message "backend must parse model output into structured fields"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("clear_risk_analysis_history"\)' -Message "backend must expose risk analysis history clearing"
Assert-Contains -Path "app.py" -Pattern 'deepseek-v4-pro' -Message "DeepSeek default/fallback models must include deepseek-v4-pro"
Assert-Contains -Path "app.py" -Pattern 'deepseek-v4-flash' -Message "DeepSeek fallback models must include deepseek-v4-flash"
Assert-Contains -Path "app.py" -Pattern '_models_url' -Message "backend must request provider model lists through /models"
Assert-Contains -Path "app.py" -Pattern 'thinking' -Message "deepseek-v4-pro requests must enable thinking parameters"
Assert-Contains -Path "templates\index.html" -Pattern 'riskAnalyzeButton' -Message "frontend must expose a risk analysis button"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskBackdrop"' -Message "frontend must contain a risk analysis dialog"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabRisk' -Message "settings dialog must expose a risk analysis settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''request_risk_analysis''' -Message "frontend must trigger risk analysis manually"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''risk_analysis_result''' -Message "frontend must render risk analysis results"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''open_risk_analysis''' -Message "frontend must open risk analysis from native floating menu"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskScorecard"' -Message "frontend must render the risk scorecard"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskStructured"' -Message "frontend must render structured risk analysis fields"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskForceRunButton"' -Message "frontend must allow users to force rerun a cached analysis"
Assert-Contains -Path "templates\index.html" -Pattern 'riskQuality' -Message "frontend must render data quality"
Assert-Contains -Path "templates\index.html" -Pattern 'riskTrends' -Message "frontend must render multiple trend periods"
Assert-Contains -Path "templates\index.html" -Pattern 'analyzeActiveAlert' -Message "alert dialogs must support one-click risk analysis"
Assert-Contains -Path "templates\index.html" -Pattern 'riskAnalysisHistory' -Message "frontend must render session/local risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern 'clearRiskHistory' -Message "frontend must allow clearing risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern 'copyRiskReport' -Message "frontend must support copying risk reports"
Assert-Contains -Path "templates\index.html" -Pattern 'exportRiskReport' -Message "frontend must support exporting risk reports"
Assert-Contains -Path "templates\index.html" -Pattern 'testRiskModel' -Message "frontend must expose a model diagnostic action"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''risk_model_test_result''' -Message "frontend must render model diagnostic results"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''risk_analysis_cache_hit''' -Message "frontend must render repeated-analysis cache hits"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''get_risk_model_options''' -Message "frontend must request model options for the dropdown"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''risk_model_options_updated''' -Message "frontend must receive model option updates"
Assert-Contains -Path "templates\index.html" -Pattern 'id="setDeepseekModel"></select>' -Message "DeepSeek model must be selected from a dropdown"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskMaxTokens' -Message "risk settings must expose max token control"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskCooldownSeconds' -Message "risk settings must expose cooldown control"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskCacheMinutes' -Message "risk settings must expose repeated-analysis cache control"
Assert-Contains -Path "templates\index.html" -Pattern 'openai_compatible' -Message "frontend settings must expose compatible provider fields"
Assert-NotContains -Path "templates\index.html" -Pattern 'appSettings\.deepseek_api_key([^A-Za-z0-9_]|$)' -Message "frontend must not use a raw DeepSeek API key setting"
Assert-NotContains -Path "templates\index.html" -Pattern 'appSettings\.openai_compatible_api_key([^A-Za-z0-9_]|$)' -Message "frontend must not use a raw compatible provider API key setting"
Assert-Contains -Path "app.py" -Pattern 'alert_cooldown_minutes' -Message "settings must support alert cooldown"
Assert-Contains -Path "app.py" -Pattern 'alert_quiet_start' -Message "settings must support alert quiet start"
Assert-Contains -Path "app.py" -Pattern 'email_subject_template' -Message "settings must support email subject templates"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("test_alert"\)' -Message "backend must expose manual test alerts"
Assert-Contains -Path "templates\index.html" -Pattern 'testAlert' -Message "frontend must expose manual test alerts"
Assert-Contains -Path "app.py" -Pattern 'PRICE_HISTORY_PATH' -Message "app.py must persist price history locally"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_price_history"\)' -Message "backend must expose price history lookup"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("export_price_history"\)' -Message "backend must expose price history export"
Assert-Contains -Path "templates\index.html" -Pattern 'openHistory' -Message "frontend must expose history review"
Assert-Contains -Path "templates\index.html" -Pattern 'requestChartHistory' -Message "frontend chart periods must request historical windows"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="4h"' -Message "frontend chart must expose a 4-hour period"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="7d"' -Message "frontend chart must expose a 7-day period"
Assert-Contains -Path "templates\index.html" -Pattern 'exportHistoryCsv' -Message "frontend must export price history CSV"
Assert-Contains -Path "templates\index.html" -Pattern 'main-right \{[^}]*overflow-y:auto' -Message "right sidebar must be vertically scrollable"
Assert-Contains -Path "templates\index.html" -Pattern 'right-panel \{[^}]*flex-direction:column' -Message "right sidebar cards must flow vertically"
Assert-Contains -Path "templates\index.html" -Pattern 'alertRulesList' -Message "frontend must render an alert rule list"
Assert-Contains -Path "templates\index.html" -Pattern 'renderAlertRules' -Message "frontend must derive alert rules from current thresholds"
Assert-Contains -Path "templates\index.html" -Pattern 'setActiveAlertRule' -Message "alert rules must support inline expansion"
Assert-Contains -Path "templates\index.html" -Pattern 'saveThresholdRule' -Message "alert rules must save threshold edits inline"
Assert-Contains -Path "templates\index.html" -Pattern 'saveVolatilityRule' -Message "alert rules must save volatility edits inline"
Assert-Contains -Path "templates\index.html" -Pattern 'alertRuleEmail_' -Message "alert rules must include inline email controls"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="threshold-section"' -Message "frontend must not keep the old duplicated threshold form"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="email-switches-section"' -Message "frontend must not keep the old standalone email switch section"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="volatility-section"' -Message "frontend must not keep the old standalone volatility form"
Assert-Contains -Path "templates\index.html" -Pattern 'setFloatingPreset' -Message "settings dialog must expose floating window size presets"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("get_diagnostics"\)' -Message "backend must expose diagnostics export"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("export_config"\)' -Message "backend must expose config backup"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("import_config"\)' -Message "backend must expose config import"
Assert-Contains -Path "app.py" -Pattern '@socketio\.on\("reset_settings"\)' -Message "backend must expose reset settings"
Assert-Contains -Path "app.py" -Pattern 'diagnostic_settings_snapshot' -Message "diagnostics must mask sensitive settings"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabOps' -Message "settings dialog must expose operations tab"
Assert-Contains -Path "templates\index.html" -Pattern 'exportDiagnostics' -Message "frontend must export diagnostics"
Assert-Contains -Path "templates\index.html" -Pattern 'id="priceRetry"' -Message "index.html must show a manual price retry button"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.emit\(''refresh_price''' -Message "index.html must request manual price refresh"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''fetch_status''' -Message "index.html must render fetch status"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.connect\(\)' -Message "index.html must provide a manual reconnect action"
Assert-Contains -Path "templates\index.html" -Pattern 'socket\.on\(''connect_error''' -Message "index.html must explain initial connection failures"
Assert-Contains -Path "templates\index.html" -Pattern 'rate_cached' -Message "index.html must label cached forex rates"
Assert-Contains -Path "templates\index.html" -Pattern 'gold_cached' -Message "index.html must preserve cached gold status"
Assert-Contains -Path "GoldMonitor.spec" -Pattern 'exclude_binaries=True' -Message "PyInstaller must build in onedir mode"
Assert-Contains -Path "GoldMonitor.spec" -Pattern 'COLLECT\(' -Message "PyInstaller spec must collect files into a distribution directory"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'PrivilegesRequired=lowest' -Message "installer must be per-user"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'dist\\GoldMonitor\\\*' -Message "installer must package the PyInstaller onedir output"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'AppUserModelID:\s*"GoldMonitor\.App"' -Message "installer shortcuts must set the AppUserModelID"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'desktopicon' -Message "installer must support desktop shortcut task"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'CloseApplications=force' -Message "installer must force-close a running app during updates"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'RestartApplications=no' -Message "installer must avoid relying on system restart manager relaunches"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'CloseApplicationsFilter=\{#MyAppExeName\}' -Message "installer must only close the app executable during updates"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'InitializeSetup' -Message "installer must run a pre-install close hook"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'taskkill\.exe' -Message "installer must terminate stale GoldMonitor processes before replacing files"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern '/F /IM \{#MyAppExeName\}' -Message "installer taskkill must target only the app executable"
Assert-NotContains -Path "installer\GoldMonitor.iss" -Pattern '/F /T /IM \{#MyAppExeName\}' -Message "installer must not terminate the updater child process tree"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'Filename: "\{app\}\\\{#MyAppExeName\}".*Flags: nowait' -Message "installer must launch the app after install and update"
Assert-NotContains -Path "installer\GoldMonitor.iss" -Pattern 'skipifsilent' -Message "silent updates must not skip launching the app after install"

Write-Host "Contract checks passed."
