$ErrorActionPreference = "Stop"

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -notmatch $Pattern) {
        throw $Message
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -match $Pattern) {
        throw $Message
    }
}

Assert-Contains -Path "app.py" -Pattern "settings\.json" -Message "app.py must persist settings to settings.json"
Assert-Contains -Path "app.py" -Pattern "find_available_port" -Message "app.py must avoid stale services by selecting an available port"
Assert-Contains -Path "app.py" -Pattern "startup_enabled" -Message "app.py must define startup_enabled"
Assert-Contains -Path "app.py" -Pattern "floating_price_enabled" -Message "app.py must support a desktop floating price setting"
Assert-Contains -Path "app.py" -Pattern "floating_price_position_saved" -Message "app.py must ignore stale floating price coordinates without a saved-position marker"
Assert-Contains -Path "app.py" -Pattern "floating_price_x" -Message "app.py must persist the floating price x coordinate"
Assert-Contains -Path "app.py" -Pattern "floating_price_y" -Message "app.py must persist the floating price y coordinate"
Assert-Contains -Path "app.py" -Pattern "GoldMonitorFloatingPriceWindow" -Message "app.py must create a native floating price window"
Assert-Contains -Path "app.py" -Pattern "update_floating_price" -Message "price refreshes must update the floating price window"
Assert-Contains -Path "app.py" -Pattern "WM_LBUTTONDOWN" -Message "floating price window must handle drag start"
Assert-Contains -Path "app.py" -Pattern "WM_MOUSEMOVE" -Message "floating price window must handle dragging"
Assert-Contains -Path "app.py" -Pattern "WM_RBUTTONUP" -Message "floating price window must handle right-click menus"
Assert-Contains -Path "app.py" -Pattern "WM_CONTEXTMENU" -Message "floating price window must handle context menu messages"
Assert-Contains -Path "app.py" -Pattern "TrackPopupMenu" -Message "floating price window must show a native context menu"
Assert-Contains -Path "app.py" -Pattern "FLOATING_MENU_RISK" -Message "floating price context menu must expose risk analysis"
Assert-Contains -Path "app.py" -Pattern "_floating_status_text" -Message "floating price window must show update time and source status"
Assert-Contains -Path "app.py" -Pattern "_floating_trend_state" -Message "floating price window must color price by trend"
Assert-Contains -Path "app.py" -Pattern "global _floating_drag_state" -Message "floating price drag state must be shared across Win32 mouse messages"
Assert-Contains -Path "app.py" -Pattern "_save_floating_position" -Message "floating price window must persist dragged position"
Assert-Contains -Path "app.py" -Pattern "_floating_positioned" -Message "floating price refreshes must not force repositioning after initial placement"
Assert-Contains -Path "app.py" -Pattern "Software\\Microsoft\\Windows\\CurrentVersion\\Run" -Message "app.py must manage HKCU Run startup"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""get_settings""\)" -Message "app.py must expose get_settings socket event"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""update_settings""\)" -Message "app.py must expose update_settings socket event"
Assert-Contains -Path "app.py" -Pattern "--startup" -Message "app.py must support --startup"
Assert-Contains -Path "app.py" -Pattern "REQUEST_TIMEOUT" -Message "app.py must use a short network request timeout"
Assert-NotContains -Path "app.py" -Pattern "cors_allowed_origins\s*=\s*""\*""" -Message "Socket.IO must not allow every browser origin"
Assert-Contains -Path "app.py" -Pattern "SOCKET_ACCESS_TOKEN" -Message "Socket.IO clients must use a per-process access token"
Assert-Contains -Path "templates\index.html" -Pattern "auth:\s*\{\s*token:\s*SOCKET_ACCESS_TOKEN\s*\}" -Message "frontend must send the Socket.IO access token"
Assert-Contains -Path "app.py" -Pattern "APP_USER_MODEL_ID\s*=\s*""GoldMonitor\.App""" -Message "app.py must define the Windows AppUserModelID"
Assert-Contains -Path "app.py" -Pattern "app_id=APP_USER_MODEL_ID" -Message "desktop toast must use the application AppUserModelID"
Assert-Contains -Path "app.py" -Pattern "icon=notification_icon" -Message "desktop toast must include the app icon"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""close_choice""\)" -Message "app.py must receive close choices from the frontend"
Assert-Contains -Path "app.py" -Pattern "socketio\.emit\(""show_close_dialog""" -Message "app.py must ask the frontend to show close confirmation"
Assert-Contains -Path "app.py" -Pattern "hide_main_window" -Message "app.py must hide the pywebview window to tray"
Assert-Contains -Path "app.py" -Pattern "SW_HIDE" -Message "app.py must use a Win32 hide fallback for tray minimization"
Assert-NotContains -Path "app.py" -Pattern "import tkinter" -Message "app.py must not depend on tkinter in packaged runtime"
Assert-Contains -Path "app.py" -Pattern "show_alert_dialog" -Message "app.py must show system alert dialog"
Assert-Contains -Path "templates\index.html" -Pattern "openSettings" -Message "index.html must expose a settings entry"
Assert-Contains -Path "templates\index.html" -Pattern "settingsTabGeneral" -Message "settings dialog must expose a general settings tab"
Assert-Contains -Path "templates\index.html" -Pattern "setFloatingPrice" -Message "settings dialog must expose a floating price toggle"
Assert-Contains -Path "templates\index.html" -Pattern "settingsTabEmail" -Message "settings dialog must expose an email settings tab"
Assert-Contains -Path "templates\index.html" -Pattern "switchSettingsTab" -Message "settings dialog must support switching sections"
Assert-Contains -Path "templates\index.html" -Pattern "settings-body \{[^}]*overflow-y:auto" -Message "settings dialog body must support scrolling"
Assert-Contains -Path "templates\index.html" -Pattern "settings-foot \{[^}]*flex:0 0 auto" -Message "settings dialog actions must remain fixed outside the scroll body"
Assert-Contains -Path "templates\index.html" -Pattern "update_settings" -Message "index.html must save settings"
Assert-Contains -Path "templates\index.html" -Pattern "id=""closeBackdrop""" -Message "index.html must contain an app close confirmation dialog"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('show_close_dialog'" -Message "index.html must handle backend close confirmation requests"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('close_choice'" -Message "index.html must send close choices to the backend"
Assert-Contains -Path "templates\index.html" -Pattern "id=""alertBackdrop""" -Message "index.html must contain an app alert dialog"
Assert-Contains -Path "templates\index.html" -Pattern "showAlertModal" -Message "index.html must show app alert dialogs from alert events"
Assert-Contains -Path "templates\index.html" -Pattern "max-width:none" -Message "layout must use the available window width"
Assert-Contains -Path "templates\index.html" -Pattern "grid-template-columns:minmax\(0, 1fr\) var\(--right-width\)" -Message "layout must use responsive grid columns"
Assert-Contains -Path "templates\index.html" -Pattern "@media \(max-width:1100px\)" -Message "layout must switch at medium widths"
Assert-Contains -Path "templates\index.html" -Pattern "height:100vh" -Message "layout must lock the app to one viewport"
Assert-Contains -Path "templates\index.html" -Pattern "overflow:hidden" -Message "layout must avoid page-level scrolling"
Assert-Contains -Path "templates\index.html" -Pattern "openUpdate" -Message "index.html must expose an update entry"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('check_update'" -Message "index.html must request update checks"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('install_update'" -Message "index.html must request update install"
Assert-NotContains -Path "templates\index.html" -Pattern "socket\.emit\('install_update',\s*pendingUpdateInfo\)" -Message "frontend must not send installer URLs back to install_update"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('update_status'" -Message "index.html must handle update status"
Assert-Contains -Path "app.py" -Pattern "APP_VERSION" -Message "app.py must expose a current app version"
Assert-Contains -Path "app.py" -Pattern "update_manifest_url" -Message "settings must support an update manifest url"
Assert-Contains -Path "app.py" -Pattern "compare_versions" -Message "app.py must compare update versions"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""check_update""\)" -Message "app.py must expose check_update socket event"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""install_update""\)" -Message "app.py must expose install_update socket event"
Assert-Contains -Path "app.py" -Pattern "GoldMonitorSetup" -Message "updater must download the setup executable"
Assert-Contains -Path "app.py" -Pattern "NEWS_CACHE_PATH" -Message "app.py must cache gold-related news locally"
Assert-Contains -Path "app.py" -Pattern "THRESHOLDS_PATH" -Message "app.py must persist thresholds locally"
Assert-Contains -Path "app.py" -Pattern "load_thresholds" -Message "app.py must load thresholds from disk"
Assert-Contains -Path "app.py" -Pattern "save_thresholds" -Message "app.py must save thresholds to disk"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""refresh_price""\)" -Message "app.py must expose manual price refresh"
Assert-Contains -Path "app.py" -Pattern "last_fetch_error" -Message "app.py must track fetch failure reasons"
Assert-Contains -Path "app.py" -Pattern "fetch_status" -Message "app.py must expose fetch status"
Assert-Contains -Path "app.py" -Pattern "MARKET_CACHE_PATH" -Message "app.py must cache market rates locally"
Assert-Contains -Path "app.py" -Pattern "SINA_GOLD_URL" -Message "app.py must include Sina gold source"
Assert-Contains -Path "app.py" -Pattern "parse_sina_gold" -Message "app.py must parse Sina gold data"
Assert-Contains -Path "app.py" -Pattern "save_xauusd_cache" -Message "app.py must cache successful XAU/USD prices locally"
Assert-Contains -Path "app.py" -Pattern "load_valid_xauusd_cache" -Message "app.py must reuse fresh cached XAU/USD prices when live sources fail"
Assert-Contains -Path "app.py" -Pattern "fetch_usdcny_rate_result" -Message "app.py must fetch USD/CNY from multiple sources"
Assert-Contains -Path "app.py" -Pattern "parse_sina_forex" -Message "app.py must parse Sina USD/CNY rates"
Assert-Contains -Path "app.py" -Pattern "parse_frankfurter_forex" -Message "app.py must parse Frankfurter USD/CNY rates"
Assert-Contains -Path "app.py" -Pattern "rate_cached" -Message "price updates must expose cached rate status"
Assert-Contains -Path "app.py" -Pattern "GDELT" -Message "app.py must include a public gold news source"
Assert-Contains -Path "app.py" -Pattern "press_all\.xml" -Message "app.py must include the Federal Reserve RSS feed"
Assert-Contains -Path "app.py" -Pattern "bls_latest\.rss" -Message "app.py must include the BLS RSS feed"
Assert-Contains -Path "app.py" -Pattern "def fetch_gold_news" -Message "app.py must fetch gold-related news"
Assert-Contains -Path "app.py" -Pattern "def start_news_fetching" -Message "app.py must refresh news in the background"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""get_news""\)" -Message "app.py must expose get_news socket event"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""refresh_news""\)" -Message "app.py must expose refresh_news socket event"
Assert-Contains -Path "app.py" -Pattern "news_updated" -Message "app.py must emit news updates to the frontend"
Assert-Contains -Path "app.py" -Pattern "related_news" -Message "alerts must include related news candidates"
Assert-NotContains -Path "templates\index.html" -Pattern "newsButton" -Message "index.html must not expose a gold news toolbar entry"
Assert-NotContains -Path "templates\index.html" -Pattern "id=""newsBackdrop""" -Message "index.html must not expose the gold news panel"
Assert-NotContains -Path "templates\index.html" -Pattern "openNews" -Message "index.html must not expose a gold news entry"
Assert-NotContains -Path "templates\index.html" -Pattern "socket\.emit\('get_news'" -Message "index.html must not request manual news panel data"
Assert-NotContains -Path "templates\index.html" -Pattern "socket\.emit\('refresh_news'" -Message "index.html must not request manual news refresh"
Assert-Contains -Path "templates\index.html" -Pattern "related-news" -Message "alert dialog must render related news"
Assert-Contains -Path "app.py" -Pattern "risk_assistant_enabled" -Message "settings must support a risk assistant toggle"
Assert-Contains -Path "app.py" -Pattern "deepseek_base_url" -Message "settings must support a DeepSeek API base url"
Assert-Contains -Path "app.py" -Pattern "deepseek_model" -Message "settings must support a DeepSeek model"
Assert-Contains -Path "app.py" -Pattern "deepseek_api_key" -Message "settings must persist the DeepSeek API key locally"
Assert-Contains -Path "app.py" -Pattern "public_settings_snapshot" -Message "backend must expose a sanitized public settings snapshot"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""request_risk_analysis""\)" -Message "backend must expose a manual risk analysis socket event"
Assert-Contains -Path "app.py" -Pattern "build_risk_analysis_context" -Message "backend must build a read-only risk analysis context"
Assert-Contains -Path "app.py" -Pattern "call_deepseek_risk_analysis" -Message "backend must call DeepSeek for risk analysis"
Assert-Contains -Path "app.py" -Pattern "risk_scorecard" -Message "risk assistant context must include a scorecard"
Assert-Contains -Path "app.py" -Pattern "data_quality" -Message "risk assistant context must include data quality"
Assert-Contains -Path "app.py" -Pattern "multi_period_trends" -Message "risk assistant context must include multiple trend periods"
Assert-Contains -Path "app.py" -Pattern "openai_compatible" -Message "risk assistant must keep an OpenAI-compatible provider extension point"
Assert-Contains -Path "app.py" -Pattern "openai_compatible_api_key_masked" -Message "compatible provider API keys must be masked before reaching the frontend"
Assert-Contains -Path "app.py" -Pattern "risk_assistant_max_tokens" -Message "risk assistant must expose a max-token cost control"
Assert-Contains -Path "app.py" -Pattern "risk_assistant_cooldown_seconds" -Message "risk assistant must expose a repeated-click cooldown"
Assert-Contains -Path "app.py" -Pattern "risk_assistant_cache_minutes" -Message "risk assistant must expose a repeated-analysis cache window"
Assert-Contains -Path "app.py" -Pattern "risk_analysis_history" -Message "risk assistant must keep bounded local analysis history"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""get_risk_model_options""\)" -Message "backend must expose model option lookup"
Assert-Contains -Path "app.py" -Pattern "risk_model_options_updated" -Message "backend must emit model option lookup results"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""test_risk_model""\)" -Message "backend must expose model availability diagnostics"
Assert-Contains -Path "app.py" -Pattern "risk_model_test_result" -Message "backend must emit model diagnostic results"
Assert-Contains -Path "app.py" -Pattern "risk_analysis_cache_hit" -Message "backend must emit repeated-analysis cache hits"
Assert-Contains -Path "app.py" -Pattern "parse_risk_analysis_sections" -Message "backend must parse model output into structured fields"
Assert-Contains -Path "app.py" -Pattern "@socketio\.on\(""clear_risk_analysis_history""\)" -Message "backend must expose risk analysis history clearing"
Assert-Contains -Path "app.py" -Pattern "deepseek-v4-pro" -Message "DeepSeek default/fallback models must include deepseek-v4-pro"
Assert-Contains -Path "app.py" -Pattern "deepseek-v4-flash" -Message "DeepSeek fallback models must include deepseek-v4-flash"
Assert-Contains -Path "app.py" -Pattern "_models_url" -Message "backend must request provider model lists through /models"
Assert-Contains -Path "app.py" -Pattern "thinking" -Message "deepseek-v4-pro requests must enable thinking parameters"
Assert-Contains -Path "templates\index.html" -Pattern "riskAnalyzeButton" -Message "frontend must expose a risk analysis button"
Assert-Contains -Path "templates\index.html" -Pattern "id=""riskBackdrop""" -Message "frontend must contain a risk analysis dialog"
Assert-Contains -Path "templates\index.html" -Pattern "settingsTabRisk" -Message "settings dialog must expose a risk analysis settings tab"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('request_risk_analysis'" -Message "frontend must trigger risk analysis manually"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('risk_analysis_result'" -Message "frontend must render risk analysis results"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('open_risk_analysis'" -Message "frontend must open risk analysis from native floating menu"
Assert-Contains -Path "templates\index.html" -Pattern "id=""riskScorecard""" -Message "frontend must render the risk scorecard"
Assert-Contains -Path "templates\index.html" -Pattern "id=""riskStructured""" -Message "frontend must render structured risk analysis fields"
Assert-Contains -Path "templates\index.html" -Pattern "id=""riskForceRunButton""" -Message "frontend must allow users to force rerun a cached analysis"
Assert-Contains -Path "templates\index.html" -Pattern "riskQuality" -Message "frontend must render data quality"
Assert-Contains -Path "templates\index.html" -Pattern "riskTrends" -Message "frontend must render multiple trend periods"
Assert-Contains -Path "templates\index.html" -Pattern "analyzeActiveAlert" -Message "alert dialogs must support one-click risk analysis"
Assert-Contains -Path "templates\index.html" -Pattern "riskAnalysisHistory" -Message "frontend must render session/local risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern "clearRiskHistory" -Message "frontend must allow clearing risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern "testRiskModel" -Message "frontend must expose a model diagnostic action"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('risk_model_test_result'" -Message "frontend must render model diagnostic results"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('risk_analysis_cache_hit'" -Message "frontend must render repeated-analysis cache hits"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('get_risk_model_options'" -Message "frontend must request model options for the dropdown"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('risk_model_options_updated'" -Message "frontend must receive model option updates"
Assert-Contains -Path "templates\index.html" -Pattern "id=""setDeepseekModel""></select>" -Message "DeepSeek model must be selected from a dropdown"
Assert-Contains -Path "templates\index.html" -Pattern "setRiskMaxTokens" -Message "risk settings must expose max token control"
Assert-Contains -Path "templates\index.html" -Pattern "setRiskCooldownSeconds" -Message "risk settings must expose cooldown control"
Assert-Contains -Path "templates\index.html" -Pattern "setRiskCacheMinutes" -Message "risk settings must expose repeated-analysis cache control"
Assert-Contains -Path "templates\index.html" -Pattern "openai_compatible" -Message "frontend settings must expose compatible provider fields"
Assert-NotContains -Path "templates\index.html" -Pattern "appSettings\.deepseek_api_key([^A-Za-z0-9_]|$)" -Message "frontend must not use a raw DeepSeek API key setting"
Assert-NotContains -Path "templates\index.html" -Pattern "appSettings\.openai_compatible_api_key([^A-Za-z0-9_]|$)" -Message "frontend must not use a raw compatible provider API key setting"
Assert-Contains -Path "templates\index.html" -Pattern "id=""priceRetry""" -Message "index.html must show a manual price retry button"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.emit\('refresh_price'" -Message "index.html must request manual price refresh"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('fetch_status'" -Message "index.html must render fetch status"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.connect\(\)" -Message "index.html must provide a manual reconnect action"
Assert-Contains -Path "templates\index.html" -Pattern "socket\.on\('connect_error'" -Message "index.html must explain initial connection failures"
Assert-Contains -Path "templates\index.html" -Pattern "rate_cached" -Message "index.html must label cached forex rates"
Assert-Contains -Path "templates\index.html" -Pattern "gold_cached" -Message "index.html must preserve cached gold status"
Assert-Contains -Path "GoldMonitor.spec" -Pattern "exclude_binaries=True" -Message "PyInstaller must build in onedir mode"
Assert-Contains -Path "GoldMonitor.spec" -Pattern "COLLECT\(" -Message "PyInstaller spec must collect files into a distribution directory"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern "PrivilegesRequired=lowest" -Message "installer must be per-user"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern "dist\\GoldMonitor\\\*" -Message "installer must package the PyInstaller onedir output"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern "AppUserModelID:\s*""GoldMonitor\.App""" -Message "installer shortcuts must set the AppUserModelID"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern "desktopicon" -Message "installer must support desktop shortcut task"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern "CloseApplications=yes" -Message "installer must support replacing a running app during updates"

Write-Host "Contract checks passed."
