$ErrorActionPreference = "Stop"

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -notmatch $Pattern) {
        throw $Message
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Message
    )

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -match $Pattern) {
        throw $Message
    }
}

Assert-Contains -Path "goldmonitor\application.py" -Pattern 'settings\.json' -Message "app.py must persist settings to settings.json"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'find_available_port' -Message "app.py must avoid stale services by selecting an available port"
Assert-Contains -Path "goldmonitor\instance_runtime.py" -Pattern 'def find_existing_instance' -Message "instance runtime must identify an existing application process"
Assert-Contains -Path "goldmonitor\instance_runtime.py" -Pattern 'def wait_for_server_ready' -Message "instance runtime must coordinate local server readiness"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'startup_enabled' -Message "app.py must define startup_enabled"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_enabled' -Message "app.py must support a desktop floating price setting"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_windows_mode' -Message "app.py must support Windows floating and taskbar display modes"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'Shell_TrayWnd' -Message "taskbar runtime must discover the Windows taskbar"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'TrayNotifyWnd' -Message "taskbar runtime must protect the notification area"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'MSTaskListWClass' -Message "taskbar runtime must protect task buttons"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'WS_EX_NOACTIVATE' -Message "taskbar price window must not activate on display"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'ABM_GETSTATE' -Message "taskbar runtime must detect auto-hide mode"
Assert-Contains -Path "goldmonitor\taskbar_runtime.py" -Pattern 'GoldMonitorTaskbarPriceWindow' -Message "taskbar runtime must create a native taskbar price window"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'save_window_position' -Message "floating controller must persist dragged window coordinates"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'floating_price_position_saved' -Message "floating runtime must ignore stale coordinates without a saved-position marker"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_opacity' -Message "floating price settings must support opacity"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_display_mode' -Message "floating price settings must support display modes"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_preset' -Message "floating price settings must support size presets"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'VALID_FLOATING_PRESETS' -Message "floating price presets must be validated"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_snap_edge' -Message "floating price settings must support edge snapping"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_always_on_top' -Message "floating price settings must support optional topmost mode"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_hide_on_fullscreen' -Message "floating price settings must support automatic fullscreen hiding"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'floating_price_lock_position' -Message "floating price settings must support position locking"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'HWND_NOTOPMOST' -Message "floating price window must default to non-topmost mode"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'floating_window_z_order' -Message "floating price window must choose z-order from settings"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'is_foreground_window_fullscreen' -Message "floating price window must detect other fullscreen applications"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'FLOATING_VISIBILITY_TIMER_ID' -Message "floating price window must refresh fullscreen visibility state"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'GoldMonitorFloatingPriceWindow' -Message "floating runtime must create a native floating price window"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'update_floating_price' -Message "price refreshes must update the floating price window"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'WM_LBUTTONDOWN' -Message "floating price window must handle drag start"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'WM_LBUTTONDBLCLK' -Message "floating price window must open the main window on double click"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'CS_DBLCLKS' -Message "floating price window class must opt in to double-click messages"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'WM_MOUSEMOVE' -Message "floating price window must handle dragging"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'WM_RBUTTONUP' -Message "floating price window must handle right-click menus"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'WM_CONTEXTMENU' -Message "floating price window must handle context menu messages"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'TrackPopupMenu' -Message "floating price window must show a native context menu"
Assert-Contains -Path "goldmonitor\floating_runtime.py" -Pattern 'FLOATING_MENU_RISK' -Message "floating price context menu must expose risk analysis"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'runtime\.floating_status_text' -Message "floating controller must maintain update time and source status"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'runtime\.floating_trend_state' -Message "floating controller must maintain the displayed price trend"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'runtime\.floating_drag_state' -Message "floating price drag state must be shared across Win32 mouse messages"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'save_position' -Message "floating controller must persist dragged position"
Assert-Contains -Path "goldmonitor\floating_controller.py" -Pattern 'runtime\.floating_positioned' -Message "floating price refreshes must not force repositioning after initial placement"
Assert-Contains -Path "goldmonitor\application.py" -Pattern '_refresh_price_from_tray_menu' -Message "tray menu must support manual price refresh"
Assert-Contains -Path "goldmonitor\application.py" -Pattern '_open_risk_analysis_from_tray_menu' -Message "tray menu must support risk analysis"
Assert-Contains -Path "goldmonitor\application.py" -Pattern '_toggle_floating_price_from_tray_menu' -Message "tray menu must support floating price toggle"
Assert-Contains -Path "goldmonitor\desktop_runtime.py" -Pattern '刷新行情' -Message "tray menu must render a refresh action"
Assert-Contains -Path "goldmonitor\desktop_runtime.py" -Pattern '风险分析' -Message "tray menu must render a risk analysis action"
Assert-Contains -Path "goldmonitor\desktop_runtime.py" -Pattern '切换悬浮条' -Message "tray menu must render a floating price toggle action"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Message "app.py must manage HKCU Run startup"
Assert-Contains -Path "goldmonitor\socket_settings.py" -Pattern '@socketio\.on\("get_settings"\)' -Message "app.py must expose get_settings socket event"
Assert-Contains -Path "goldmonitor\socket_settings.py" -Pattern '@socketio\.on\("update_settings"\)' -Message "app.py must expose update_settings socket event"
Assert-Contains -Path "goldmonitor\application_bootstrap.py" -Pattern '--startup' -Message "startup bootstrap must support --startup"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'REQUEST_TIMEOUT' -Message "app.py must use a short network request timeout"
Assert-NotContains -Path "goldmonitor\application.py" -Pattern 'cors_allowed_origins\s*=\s*"\*"' -Message "Socket.IO must not allow every browser origin"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'SOCKET_ACCESS_TOKEN' -Message "Socket.IO clients must use a per-process access token"
Assert-Contains -Path "static\app-state.js" -Pattern 'auth:\s*\{\s*token:\s*SOCKET_ACCESS_TOKEN\s*\}' -Message "frontend must send the Socket.IO access token"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'APP_USER_MODEL_ID\s*=\s*"GoldMonitor\.App"' -Message "app.py must define the Windows AppUserModelID"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'MACOS_LAUNCH_AGENT_ID' -Message "app.py must define the macOS LaunchAgent identifier"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'create_macos_status_item' -Message "app.py must expose a macOS menu bar status item"
Assert-Contains -Path "goldmonitor\notification_runtime.py" -Pattern 'display notification' -Message "notification runtime must support macOS notification center alerts"
Assert-Contains -Path "goldmonitor\notification_runtime.py" -Pattern 'afplay' -Message "notification runtime must support macOS alert sounds"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'app_id=APP_USER_MODEL_ID' -Message "desktop toast must use the application AppUserModelID"
Assert-Contains -Path "goldmonitor\notification_runtime.py" -Pattern 'icon=icon' -Message "desktop toast must include the app icon"
Assert-Contains -Path "goldmonitor\socket_runtime.py" -Pattern '"close_choice": on_close_choice' -Message "socket runtime must receive close choices from the frontend"
Assert-Contains -Path "goldmonitor\desktop_runtime.py" -Pattern 'emit\("show_close_dialog"' -Message "desktop runtime must ask the frontend to show close confirmation"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'hide_main_window' -Message "app.py must hide the pywebview window to tray"
Assert-Contains -Path "goldmonitor\desktop_runtime.py" -Pattern 'SW_HIDE' -Message "desktop runtime must use a Win32 hide fallback for tray minimization"
Assert-NotContains -Path "goldmonitor\application.py" -Pattern 'import tkinter' -Message "app.py must not depend on tkinter in packaged runtime"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'show_alert_dialog' -Message "app.py must show system alert dialog"
Assert-Contains -Path "goldmonitor\application.py" -Pattern '_alert_dialog_lock' -Message "system alert dialog must guard against stacked message boxes"
Assert-Contains -Path "templates\index.html" -Pattern 'openSettings' -Message "index.html must expose a settings entry"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabGeneral' -Message "settings dialog must expose a general settings tab"
Assert-Contains -Path "static\settings-render.js" -Pattern 'applyPlatformLabels' -Message "settings dialog must adapt platform-specific labels"
Assert-Contains -Path "static\settings-render.js" -Pattern '隐藏到菜单栏' -Message "macOS close dialog must mention hiding to the menu bar"
Assert-Contains -Path "templates\index.html" -Pattern 'setFloatingPrice' -Message "settings dialog must expose a floating price toggle"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabEmail' -Message "settings dialog must expose an email settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabWebhook' -Message "settings dialog must expose a webhook settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabDigest' -Message "settings dialog must expose a daily digest settings tab"
Assert-Contains -Path "templates\index.html" -Pattern 'setDailyDigestEnabled' -Message "daily digest settings must expose an enable toggle"
Assert-Contains -Path "templates\index.html" -Pattern 'setDailyDigestTime' -Message "daily digest settings must expose a local send time"
Assert-Contains -Path "templates\index.html" -Pattern 'setDailyDigestEmail' -Message "daily digest settings must expose an email channel toggle"
Assert-Contains -Path "templates\index.html" -Pattern 'setDailyDigestWebhook' -Message "daily digest settings must expose a webhook channel toggle"
Assert-Contains -Path "templates\index.html" -Pattern 'btnPreviewDailyDigest' -Message "daily digest settings must expose a preview action"
Assert-Contains -Path "templates\index.html" -Pattern 'btnTestDailyDigest' -Message "daily digest settings must expose a manual test action"
Assert-Contains -Path "static\settings-actions.js" -Pattern 'preview_daily_digest' -Message "frontend must request daily digest previews"
Assert-Contains -Path "static\settings-actions.js" -Pattern 'test_daily_digest' -Message "frontend must request manual daily digest delivery"
Assert-Contains -Path "static\settings-socket.js" -Pattern 'daily_digest_status' -Message "frontend must render daily digest status"
Assert-Contains -Path "static\settings-socket.js" -Pattern 'daily_digest_previewed' -Message "frontend must render daily digest previews"
Assert-Contains -Path "static\settings-socket.js" -Pattern 'daily_digest_test_result' -Message "frontend must render daily digest test results"
Assert-Contains -Path "static\settings-form.js" -Pattern 'get_daily_digest_status' -Message "frontend must refresh daily digest status when its settings tab opens"
Assert-Contains -Path "templates\index.html" -Pattern 'switchSettingsTab' -Message "settings dialog must support switching sections"
Assert-Contains -Path "static\app.css" -Pattern 'settings-body \{[^}]*overflow-y:auto' -Message "settings dialog body must support scrolling"
Assert-Contains -Path "static\app.css" -Pattern 'settings-foot \{[^}]*flex:0 0 auto' -Message "settings dialog actions must remain fixed outside the scroll body"
Assert-Contains -Path "static\settings-actions.js" -Pattern 'update_settings' -Message "index.html must save settings"
Assert-Contains -Path "templates\index.html" -Pattern 'id="closeBackdrop"' -Message "index.html must contain an app close confirmation dialog"
Assert-Contains -Path "static\app.js" -Pattern 'socket\.on\(''show_close_dialog''' -Message "index.html must handle backend close confirmation requests"
Assert-Contains -Path "static\desktop-close.js" -Pattern 'socket\.emit\(''close_choice''' -Message "index.html must send close choices to the backend"
Assert-Contains -Path "templates\index.html" -Pattern 'id="alertBackdrop"' -Message "index.html must contain an app alert dialog"
Assert-Contains -Path "static\alert-log-center.js" -Pattern 'showAlertModal' -Message "index.html must show app alert dialogs from alert events"
Assert-Contains -Path "static\alert-log-center.js" -Pattern 'mergedAlertCount' -Message "alert dialogs must merge repeated alerts into one visible dialog"
Assert-NotContains -Path "templates\index.html" -Pattern 'alertQueue' -Message "alert dialogs must not queue repeated modal popups"
Assert-Contains -Path "static\app.css" -Pattern 'max-width:none' -Message "layout must use the available window width"
Assert-Contains -Path "static\app.css" -Pattern 'grid-template-columns:minmax\(0, 1fr\) var\(--right-width\)' -Message "layout must use responsive grid columns"
Assert-Contains -Path "static\app.css" -Pattern '@media \(max-width:1100px\)' -Message "layout must switch at medium widths"
Assert-Contains -Path "static\app.css" -Pattern 'height:100vh' -Message "layout must lock the app to one viewport"
Assert-Contains -Path "static\app.css" -Pattern 'overflow:hidden' -Message "layout must avoid page-level scrolling"
Assert-Contains -Path "templates\index.html" -Pattern 'openUpdate' -Message "index.html must expose an update entry"
Assert-Contains -Path "static\operations-update.js" -Pattern 'socket\.emit\(''check_update''' -Message "index.html must request update checks"
Assert-Contains -Path "static\operations-state.js" -Pattern 'AUTO_UPDATE_CHECK_INTERVAL_MS' -Message "index.html must define automatic update check interval"
Assert-Contains -Path "static\operations-update.js" -Pattern 'scheduleAutoUpdateCheck' -Message "index.html must schedule automatic update checks"
Assert-Contains -Path "static\operations-update.js" -Pattern 'socket\.emit\(''install_update''' -Message "index.html must request update install"
Assert-Contains -Path "templates\index.html" -Pattern 'updateProgress' -Message "update dialog must show download progress"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''install_update'',\s*pendingUpdateInfo\)' -Message "frontend must not send installer URLs back to install_update"
Assert-Contains -Path "static\operations-socket.js" -Pattern 'socket\.on\(''update_status''' -Message "index.html must handle update status"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'APP_VERSION' -Message "goldmonitor/application.py must expose a current app version"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'DEFAULT_UPDATE_MANIFEST_URL' -Message "app.py must define a default update source URL in code"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'get_update_manifest_url' -Message "backend must use a fixed built-in update source"
Assert-NotContains -Path "templates\index.html" -Pattern 'setUpdateManifestUrl' -Message "settings must not expose editable update source"
Assert-NotContains -Path "templates\index.html" -Pattern '更新源地址' -Message "settings must not show update source url"
Assert-NotContains -Path "templates\index.html" -Pattern 'setUpdateIntervalHours' -Message "settings must not expose update check interval"
Assert-NotContains -Path "templates\index.html" -Pattern 'data\.url' -Message "frontend update status must not consume installer url"
Assert-NotContains -Path "templates\index.html" -Pattern 'data\.sha256' -Message "frontend update status must not consume installer sha256"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'compare_versions' -Message "app.py must compare update versions"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("check_update"\)' -Message "app.py must expose check_update socket event"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("install_update"\)' -Message "app.py must expose install_update socket event"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'progress_callback' -Message "updater must report installer download progress"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'GoldMonitorSetup' -Message "updater must download the setup executable"
Assert-Contains -Path ".github\workflows\release.yml" -Pattern 'GoldMonitor-macOS\.dmg' -Message "release workflow must publish the macOS DMG"
Assert-Contains -Path "scripts\build_macos_dmg.sh" -Pattern 'hdiutil create' -Message "macOS packaging must create a DMG"
Assert-Contains -Path "scripts\generate_release_manifest.py" -Pattern 'CHANGELOG\.md' -Message "release metadata must read version notes from CHANGELOG.md"
Assert-Contains -Path "scripts\generate_release_manifest.py" -Pattern 'missing release notes' -Message "release metadata must fail when release notes are missing"
$appSource = Get-Content -Path "goldmonitor\application.py" -Raw -Encoding UTF8
$appVersionMatch = [regex]::Match($appSource, 'APP_VERSION\s*=\s*"([^"]+)"')
if (-not $appVersionMatch.Success) {
    throw "goldmonitor/application.py must expose APP_VERSION as a quoted string"
}
$currentReleasePattern = '##\s+' + [regex]::Escape($appVersionMatch.Groups[1].Value)
Assert-Contains -Path "CHANGELOG.md" -Pattern $currentReleasePattern -Message "CHANGELOG.md must document the current release"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'NEWS_CACHE_PATH' -Message "app.py must cache gold-related news locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'ALERT_RULES_PATH' -Message "app.py must persist unified alert rules locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'ALERT_PROFILES_PATH' -Message "backend must persist alert profile templates"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'load_alert_rules' -Message "app.py must load unified alert rules from disk"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'save_alert_rules' -Message "app.py must save unified alert rules to disk"
Assert-Contains -Path "goldmonitor\alert_rules.py" -Pattern 'ALERT_RULE_SCHEMA_VERSION' -Message "alert rules must expose a versioned storage contract"
Assert-Contains -Path "goldmonitor\alert_rules.py" -Pattern 'def inspect_alert_rule' -Message "alert rules must expose runtime inspection"
Assert-Contains -Path "goldmonitor\alert_rules.py" -Pattern 'def simulate_alert_rule' -Message "alert rules must expose history simulation"
Assert-Contains -Path "goldmonitor\alert_rules.py" -Pattern 'def batch_update_alert_rules' -Message "alert rules must expose transactional batch operations"
Assert-Contains -Path "goldmonitor\socket_alert_rules.py" -Pattern '@socketio\.on\("batch_update_alert_rules"\)' -Message "backend must expose alert rule batch updates"
Assert-Contains -Path "goldmonitor\socket_alert_rules.py" -Pattern '@socketio\.on\("get_alert_rule_insight"\)' -Message "backend must expose per-rule insight"
Assert-Contains -Path "goldmonitor\socket_alert_rules.py" -Pattern '@socketio\.on\("simulate_alert_rule"\)' -Message "backend must expose alert rule history simulation"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("set_threshold"\)' -Message "backend must expose threshold updates"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("set_volatility"\)' -Message "backend must expose volatility updates"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("save_alert_profile"\)' -Message "backend must expose alert profile save event"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("apply_alert_profile"\)' -Message "backend must expose alert profile apply event"
Assert-Contains -Path "goldmonitor\storage_manifest.py" -Pattern 'alert_profiles' -Message "storage manifest must include alert profiles"
Assert-Contains -Path "goldmonitor\storage_manifest.py" -Pattern 'daily_digest_state' -Message "storage manifest must include daily digest state"
Assert-Contains -Path "goldmonitor\storage_manifest.py" -Pattern 'review_notes' -Message "storage manifest must include review notes"
Assert-Contains -Path "goldmonitor\review_notes.py" -Pattern 'REVIEW_NOTE_LIMIT\s*=\s*500' -Message "review notes must define the local item limit"
Assert-Contains -Path "goldmonitor\review_notes.py" -Pattern 'REVIEW_NOTE_TITLE_LIMIT\s*=\s*80' -Message "review notes must define the title limit"
Assert-Contains -Path "goldmonitor\review_notes.py" -Pattern 'REVIEW_NOTE_CONTENT_LIMIT\s*=\s*2000' -Message "review notes must define the content limit"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'DAILY_DIGEST_STATE_PATH' -Message "backend must persist daily digest state locally"
Assert-Contains -Path "goldmonitor\socket_settings.py" -Pattern '@socketio\.on\("preview_daily_digest"\)' -Message "backend must expose daily digest previews"
Assert-Contains -Path "goldmonitor\socket_settings.py" -Pattern '@socketio\.on\("test_daily_digest"\)' -Message "backend must expose manual daily digest delivery"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'start_daily_digest_scheduler' -Message "backend must start the daily digest scheduler"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'REVIEW_NOTES_PATH' -Message "backend must persist review notes locally"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("save_review_note"\)' -Message "backend must expose review note save"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("delete_review_note"\)' -Message "backend must expose review note deletion"
Assert-Contains -Path "goldmonitor\socket_runtime.py" -Pattern '"refresh_price": on_refresh_price' -Message "socket runtime must expose manual price refresh"
Assert-Contains -Path "goldmonitor\runtime_state.py" -Pattern 'last_fetch_error' -Message "runtime state must track fetch failure reasons"
Assert-Contains -Path "goldmonitor\market_runtime.py" -Pattern 'build_fetch_status' -Message "market runtime must expose fetch status"
Assert-Contains -Path "goldmonitor\runtime_state.py" -Pattern 'source_health' -Message "runtime state must retain data source health"
Assert-Contains -Path "goldmonitor\market_runtime.py" -Pattern 'record_runtime_source_health' -Message "market runtime must record source health metrics"
Assert-Contains -Path "goldmonitor\market_adapters.py" -Pattern 'class AdapterFetchResult' -Message "market adapters must expose a normalized fetch result"
Assert-Contains -Path "goldmonitor\market_adapters.py" -Pattern 'class MarketSourceAdapter' -Message "market adapters must expose a unified source adapter"
Assert-Contains -Path "goldmonitor\market_adapters.py" -Pattern 'class MarketAdapterRegistry' -Message "market adapters must expose an ordered registry"
Assert-Contains -Path "goldmonitor\market_adapters.py" -Pattern 'def fetch_http_source' -Message "market adapters must expose the shared HTTP fetch helper"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def build_market_adapter_registry' -Message "app.py must build the configured market adapter registry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def get_market_adapter_catalog' -Message "app.py must expose the market adapter catalog"
Assert-Contains -Path "goldmonitor\market_runtime.py" -Pattern 'state\["adapters"\]\s*=\s*adapters' -Message "source health must include the market adapter catalog"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'SOURCE_METRICS_PATH' -Message "source rolling metrics must persist locally"
Assert-Contains -Path "goldmonitor\market_data.py" -Pattern 'class SourceMetricsStore' -Message "market data must expose the rolling metrics store"
Assert-Contains -Path "goldmonitor\market_data.py" -Pattern 'success_rate_pct' -Message "source health must expose rolling success rate"
Assert-Contains -Path "goldmonitor\market_adapters.py" -Pattern 'def normalize_source_preferences' -Message "market adapters must validate source preferences"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("update_market_sources"\)' -Message "backend must expose market source configuration"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("retry_market_source"\)' -Message "backend must expose manual source probes"
Assert-Contains -Path "static\operations-sources.js" -Pattern 'renderSourceManager' -Message "frontend must render market source management"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("sina_gold",\s*"新浪贵金属",\s*"gold",\s*10' -Message "Sina gold adapter must keep first priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("eastmoney_gold",\s*"东方财富",\s*"gold",\s*20' -Message "Eastmoney gold adapter must keep second priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("goldprice",\s*"GoldPrice",\s*"gold",\s*30' -Message "GoldPrice adapter must keep third priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("stooq_gold",\s*"Stooq",\s*"gold",\s*40' -Message "Stooq gold adapter must keep fourth priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("sina_forex",\s*"新浪",\s*"forex",\s*10' -Message "Sina forex adapter must keep first priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("frankfurter_forex",\s*"Frankfurter",\s*"forex",\s*20' -Message "Frankfurter forex adapter must keep second priority"
Assert-Contains -Path "goldmonitor\market_clients.py" -Pattern 'adapter\("stooq_forex",\s*"Stooq",\s*"forex",\s*30' -Message "Stooq forex adapter must keep third priority"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'source_price_samples' -Message "app.py must keep source price samples for comparison"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_source_comparison_state' -Message "app.py must build data source comparison state"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'refresh_source_comparison' -Message "price refresh must update data source comparison"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'SOURCE_COMPARISON_ANOMALY_PCT' -Message "source comparison must define an anomaly threshold"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("get_source_health"\)' -Message "app.py must expose source health lookup"
Assert-Contains -Path "templates\index.html" -Pattern 'sourceHealth' -Message "frontend must render source health"
Assert-Contains -Path "templates\index.html" -Pattern 'sourceComparison' -Message "frontend must render source price comparison"
Assert-Contains -Path "static\operations-sources.js" -Pattern 'renderSourceComparison' -Message "frontend must update source price comparison"
Assert-Contains -Path "static\operations-sources.js" -Pattern 'socket\.emit\(''get_source_health''' -Message "frontend must request source health"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'MARKET_CACHE_PATH' -Message "app.py must cache market rates locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'SINA_GOLD_URL' -Message "app.py must include Sina gold source"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'parse_sina_gold' -Message "app.py must parse Sina gold data"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'save_xauusd_cache' -Message "app.py must cache successful XAU/USD prices locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'load_valid_xauusd_cache' -Message "app.py must reuse fresh cached XAU/USD prices when live sources fail"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'fetch_usdcny_rate_result' -Message "app.py must fetch USD/CNY from multiple sources"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_gold_data_result' -Message "app.py must preserve the compatible Stooq fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_csv_price_result' -Message "app.py must preserve the compatible CSV fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_sina_forex_result' -Message "app.py must preserve the compatible Sina forex fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_frankfurter_forex_result' -Message "app.py must preserve the compatible Frankfurter fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_usdcny_rate_result' -Message "app.py must preserve the compatible USD/CNY fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_sina_gold_result' -Message "app.py must preserve the compatible Sina gold fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_eastmoney_gold_result' -Message "app.py must preserve the compatible Eastmoney fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_goldprice_data_result' -Message "app.py must preserve the compatible GoldPrice fetch entry"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_market_data_result' -Message "app.py must preserve the compatible market fetch entry"
Assert-Contains -Path "goldmonitor\market_runtime.py" -Pattern 'class MarketRuntime' -Message "market runtime module must own price refresh orchestration"
Assert-Contains -Path "goldmonitor\market_runtime.py" -Pattern 'def fetch_market_data_result' -Message "market runtime module must own market source orchestration"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'parse_sina_forex' -Message "app.py must parse Sina USD/CNY rates"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'parse_frankfurter_forex' -Message "app.py must parse Frankfurter USD/CNY rates"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'rate_cached' -Message "price updates must expose cached rate status"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'GDELT' -Message "app.py must include a public gold news source"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'press_all\.xml' -Message "app.py must include the Federal Reserve RSS feed"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'bls_latest\.rss' -Message "app.py must include the BLS RSS feed"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def fetch_gold_news' -Message "app.py must fetch gold-related news"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'def start_news_fetching' -Message "app.py must refresh news in the background"
Assert-Contains -Path "goldmonitor\socket_runtime.py" -Pattern '"get_news": on_get_news' -Message "socket runtime must expose get_news socket event"
Assert-Contains -Path "goldmonitor\socket_runtime.py" -Pattern '"refresh_news": on_refresh_news' -Message "socket runtime must expose refresh_news socket event"
Assert-Contains -Path "goldmonitor\news.py" -Pattern 'news_updated' -Message "news runtime must emit updates to the frontend"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'related_news' -Message "alerts must include related news candidates"
Assert-NotContains -Path "templates\index.html" -Pattern 'newsButton' -Message "index.html must not expose a gold news toolbar entry"
Assert-NotContains -Path "templates\index.html" -Pattern 'id="newsBackdrop"' -Message "index.html must not expose the gold news panel"
Assert-NotContains -Path "templates\index.html" -Pattern 'openNews' -Message "index.html must not expose a gold news entry"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''get_news''' -Message "index.html must not request manual news panel data"
Assert-NotContains -Path "templates\index.html" -Pattern 'socket\.emit\(''refresh_news''' -Message "index.html must not request manual news refresh"
Assert-Contains -Path "templates\index.html" -Pattern 'related-news' -Message "alert dialog must render related news"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_assistant_enabled' -Message "settings must support a risk assistant toggle"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_assistant_depth' -Message "risk assistant must support analysis depth"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'deepseek_base_url' -Message "settings must support a DeepSeek API base url"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'deepseek_model' -Message "settings must support a DeepSeek model"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'deepseek_api_key' -Message "settings must persist the DeepSeek API key locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'public_settings_snapshot' -Message "backend must expose a sanitized public settings snapshot"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern '@socketio\.on\("request_risk_analysis"\)' -Message "backend must expose a manual risk analysis socket event"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_risk_analysis_context' -Message "backend must build a read-only risk analysis context"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'call_deepseek_risk_analysis' -Message "backend must call DeepSeek for risk analysis"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_scorecard' -Message "risk assistant context must include a scorecard"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'data_quality' -Message "risk assistant context must include data quality"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'multi_period_trends' -Message "risk assistant context must include multiple trend periods"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'openai_compatible' -Message "risk assistant must keep an OpenAI-compatible provider extension point"
Assert-Contains -Path "goldmonitor\settings_store.py" -Pattern 'snapshot\[f"\{key\}_masked"\]\s*=\s*mask_secret\(secret\)' -Message "compatible provider API keys must be masked before reaching the frontend"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_assistant_max_tokens' -Message "risk assistant must expose a max-token cost control"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_assistant_cooldown_seconds' -Message "risk assistant must expose a repeated-click cooldown"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_assistant_cache_minutes' -Message "risk assistant must expose a repeated-analysis cache window"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'risk_analysis_history' -Message "risk assistant must keep bounded local analysis history"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern '@socketio\.on\("get_risk_model_options"\)' -Message "backend must expose model option lookup"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern 'risk_model_options_updated' -Message "backend must emit model option lookup results"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern '@socketio\.on\("test_risk_model"\)' -Message "backend must expose model availability diagnostics"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern 'risk_model_test_result' -Message "backend must emit model diagnostic results"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern 'risk_analysis_cache_hit' -Message "backend must emit repeated-analysis cache hits"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'parse_risk_analysis_sections' -Message "backend must parse model output into structured fields"
Assert-Contains -Path "goldmonitor\socket_risk_analysis.py" -Pattern '@socketio\.on\("clear_risk_analysis_history"\)' -Message "backend must expose risk analysis history clearing"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'deepseek-v4-pro' -Message "DeepSeek default/fallback models must include deepseek-v4-pro"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'deepseek-v4-flash' -Message "DeepSeek fallback models must include deepseek-v4-flash"
Assert-Contains -Path "goldmonitor\application.py" -Pattern '_models_url' -Message "backend must request provider model lists through /models"
Assert-Contains -Path "goldmonitor\risk_analysis.py" -Pattern 'thinking' -Message "deepseek-v4-pro requests must enable thinking parameters"
Assert-Contains -Path "templates\index.html" -Pattern 'riskAnalyzeButton' -Message "frontend must expose a risk analysis button"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskBackdrop"' -Message "frontend must contain a risk analysis dialog"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabRisk' -Message "settings dialog must expose a risk analysis settings tab"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.emit\(''request_risk_analysis''' -Message "frontend must trigger risk analysis manually"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.on\(''risk_analysis_result''' -Message "frontend must render risk analysis results"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.on\(''open_risk_analysis''' -Message "frontend must open risk analysis from native floating menu"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskScorecard"' -Message "frontend must render the risk scorecard"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskStructured"' -Message "frontend must render structured risk analysis fields"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskForceRunButton"' -Message "frontend must allow users to force rerun a cached analysis"
Assert-Contains -Path "templates\index.html" -Pattern 'riskQuality' -Message "frontend must render data quality"
Assert-Contains -Path "templates\index.html" -Pattern 'riskTrends' -Message "frontend must render multiple trend periods"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskDiagnostic"' -Message "frontend must render risk analysis failure diagnostics"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_risk_analysis_error_payload' -Message "backend must emit structured risk analysis error diagnostics"
Assert-Contains -Path "goldmonitor\risk_analysis.py" -Pattern 'build_error_diagnostic' -Message "risk analysis module must classify failure reasons"
Assert-Contains -Path "templates\index.html" -Pattern 'analyzeActiveAlert' -Message "alert dialogs must support one-click risk analysis"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'riskAnalysisHistory' -Message "frontend must render session/local risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern 'clearRiskHistory' -Message "frontend must allow clearing risk analysis history"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskCompareButton"' -Message "risk history must expose a comparison action"
Assert-Contains -Path "templates\index.html" -Pattern 'id="riskComparison"' -Message "risk history must expose a comparison result region"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'riskComparisonSelection' -Message "risk history comparison must keep transient frontend selection"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'function toggleRiskComparisonItem' -Message "risk history must support selecting comparison entries"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'function compareSelectedRiskHistory' -Message "risk history must compare selected local entries"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'function renderRiskComparison' -Message "risk history must render comparison results"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern '记录一' -Message "risk history comparison must label the first record when timestamps cannot be parsed"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern '记录二' -Message "risk history comparison must label the second record when timestamps cannot be parsed"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'data-side-label' -Message "risk history comparison rows must expose their visible side labels"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'riskComparisonSelection\.length\s*(>=\s*2|>\s*1)' -Message "risk history comparison must select at most two entries"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'function applyRiskHistory[\s\S]*riskComparisonSelection\s*=\s*\[\s*\]' -Message "risk history refresh must reset comparison selection"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern '不会调用模型' -Message "risk comparison UI must state that comparison does not call the model"
Assert-Contains -Path "static\app.css" -Pattern '\.risk-comparison-row' -Message "risk comparison must expose row layout styles"
Assert-Contains -Path "static\app.css" -Pattern 'content:attr\(data-side-label\)' -Message "mobile risk comparison rows must render side labels from data attributes"
Assert-Contains -Path "static\app.css" -Pattern '@media[\s\S]*\.risk-comparison-row' -Message "risk comparison rows must include a mobile layout rule"
Assert-Contains -Path "templates\index.html" -Pattern 'copyRiskReport' -Message "frontend must support copying risk reports"
Assert-Contains -Path "templates\index.html" -Pattern 'exportRiskReport' -Message "frontend must support exporting risk reports"
Assert-Contains -Path "templates\index.html" -Pattern 'copyDiagnostics' -Message "settings ops panel must expose diagnostics copy action"
Assert-Contains -Path "static\operations-actions.js" -Pattern 'function copyDiagnostics' -Message "frontend must implement diagnostics copy action"
Assert-Contains -Path "static\operations-actions.js" -Pattern 'socket\.emit\(''copy_diagnostics''\)' -Message "frontend must request diagnostics copy text"
Assert-Contains -Path "static\operations-socket.js" -Pattern 'socket\.on\(''diagnostics_copy_ready''' -Message "frontend must handle diagnostics copy result"
Assert-Contains -Path "static\operations-socket.js" -Pattern 'navigator\.clipboard\.writeText' -Message "frontend must copy diagnostics through clipboard API"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_diagnostics_clipboard_text' -Message "backend must build copy-friendly diagnostics text"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("copy_diagnostics"\)' -Message "backend must expose diagnostics copy socket event"
Assert-Contains -Path "templates\index.html" -Pattern 'opsUpdateStatus' -Message "settings ops panel must expose update status summary"
Assert-Contains -Path "templates\index.html" -Pattern 'checkUpdateFromOps' -Message "settings ops panel must allow update checks"
Assert-Contains -Path "static\operations-update.js" -Pattern 'function renderOpsUpdateStatus' -Message "frontend must render ops update status"
Assert-Contains -Path "static\operations-update.js" -Pattern 'function checkUpdateFromOps' -Message "frontend must check updates from ops panel"
Assert-Contains -Path "static\operations-update.js" -Pattern 'function openUpdateFromOps' -Message "frontend must open update dialog from ops panel"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'record_update_status' -Message "backend must keep a sanitized runtime update status"
Assert-Contains -Path "goldmonitor\update_runtime.py" -Pattern 'def fetch_update_manifest' -Message "update runtime must own update source fallback orchestration"
Assert-Contains -Path "goldmonitor\update_runtime.py" -Pattern 'def download_update_installer' -Message "update runtime must own installer download and checksum validation"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'last_update_status' -Message "diagnostics must include last update status"
Assert-Contains -Path "templates\index.html" -Pattern 'testRiskModel' -Message "frontend must expose a model diagnostic action"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.on\(''risk_model_test_result''' -Message "frontend must render model diagnostic results"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.on\(''risk_analysis_cache_hit''' -Message "frontend must render repeated-analysis cache hits"
Assert-Contains -Path "static\settings-render.js" -Pattern 'socket\.emit\(''get_risk_model_options''' -Message "frontend must request model options for the dropdown"
Assert-Contains -Path "static\risk-analysis-center.js" -Pattern 'socket\.on\(''risk_model_options_updated''' -Message "frontend must receive model option updates"
Assert-Contains -Path "templates\index.html" -Pattern 'id="setDeepseekModel"></select>' -Message "DeepSeek model must be selected from a dropdown"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskMaxTokens' -Message "risk settings must expose max token control"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskCooldownSeconds' -Message "risk settings must expose cooldown control"
Assert-Contains -Path "templates\index.html" -Pattern 'setRiskCacheMinutes' -Message "risk settings must expose repeated-analysis cache control"
Assert-Contains -Path "templates\index.html" -Pattern 'openai_compatible' -Message "frontend settings must expose compatible provider fields"
Assert-NotContains -Path "templates\index.html" -Pattern 'appSettings\.deepseek_api_key([^A-Za-z0-9_]|$)' -Message "frontend must not use a raw DeepSeek API key setting"
Assert-NotContains -Path "templates\index.html" -Pattern 'appSettings\.openai_compatible_api_key([^A-Za-z0-9_]|$)' -Message "frontend must not use a raw compatible provider API key setting"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'alert_cooldown_minutes' -Message "settings must support alert cooldown"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'alert_quiet_start' -Message "settings must support alert quiet start"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'email_subject_template' -Message "settings must support email subject templates"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("test_alert"\)' -Message "backend must expose manual test alerts"
Assert-Contains -Path "templates\index.html" -Pattern 'testAlert' -Message "frontend must expose manual test alerts"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'PRICE_HISTORY_PATH' -Message "app.py must persist price history locally"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("get_price_history"\)' -Message "backend must expose price history lookup"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("export_price_history"\)' -Message "backend must expose price history export"
Assert-Contains -Path "templates\index.html" -Pattern 'openHistory' -Message "frontend must expose history review"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'requestChartHistory' -Message "frontend chart periods must request historical windows"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="4h"' -Message "frontend chart must expose a 4-hour period"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="7d"' -Message "frontend chart must expose a 7-day period"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="30d"' -Message "frontend chart must expose a 30-day period"
Assert-Contains -Path "templates\index.html" -Pattern 'data-period="90d"' -Message "frontend chart must expose a 90-day period"
Assert-Contains -Path "templates\index.html" -Pattern 'exportHistoryCsv' -Message "frontend must export price history CSV"
Assert-Contains -Path "static\app.css" -Pattern 'main-right \{[^}]*overflow-y:auto' -Message "right sidebar must be vertically scrollable"
Assert-Contains -Path "static\app.css" -Pattern 'right-panel \{[^}]*flex-direction:column' -Message "right sidebar cards must flow vertically"
Assert-Contains -Path "templates\index.html" -Pattern 'alertRuleCenterList' -Message "frontend must render the unified alert rule center"
Assert-Contains -Path "templates\index.html" -Pattern 'alertRuleSummary' -Message "frontend must render alert rule status summary"
Assert-Contains -Path "templates\index.html" -Pattern 'alertRuleFilters' -Message "frontend must expose alert rule type filters"
Assert-Contains -Path "templates\index.html" -Pattern 'alertProfilesPanel' -Message "frontend must render alert profile panel"
Assert-Contains -Path "templates\index.html" -Pattern 'alert-configuration-center\.js' -Message "frontend must load the alert configuration module"
Assert-Contains -Path "static\alert-rule-render.js" -Pattern 'renderAlertRuleCenter' -Message "frontend must render unified alert rules"
Assert-Contains -Path "static\alert-rule-socket.js" -Pattern 'registerAlertRuleSocketHandlers' -Message "frontend must register unified alert rule events"
Assert-Contains -Path "static\alert-configuration-center.js" -Pattern 'registerAlertConfigurationSocketHandlers' -Message "frontend must register alert configuration events"
Assert-Contains -Path "static\alert-configuration-center.js" -Pattern 'alert_profiles_updated' -Message "frontend must handle alert profile updates"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'saveUnifiedAlertRule' -Message "frontend must save unified alert rules"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'duplicateUnifiedAlertRule' -Message "frontend must duplicate unified alert rules"
Assert-Contains -Path "static\alert-rule-socket.js" -Pattern 'alertRuleDraft = rule \? cloneAlertRuleDraft\(rule\)' -Message "duplicated rules must open with a populated edit draft"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'changeAlertRuleCooldownMode' -Message "frontend must switch per-rule cooldown modes without losing the draft"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'changeAlertRuleDeliveryMode' -Message "frontend must switch per-rule delivery modes without losing the draft"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'alertRuleChannel_' -Message "alert rules must support per-rule notification channels"
Assert-Contains -Path "static\alert-rule-socket.js" -Pattern 'alert_rule_toggled' -Message "frontend must confirm alert rule toggle completion"
Assert-Contains -Path "static\alert-rule-socket.js" -Pattern 'alert_rule_reset' -Message "frontend must confirm alert rule reset completion"
Assert-Contains -Path "goldmonitor\socket_alert_rules.py" -Pattern '@socketio\.on\("save_alert_rule"\)' -Message "backend must expose unified alert rule save"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'check_alert_rules' -Message "price refresh must evaluate unified alert rules"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'WATCH_TARGETS_PATH' -Message "app.py must persist watch targets locally"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'load_watch_targets' -Message "app.py must load watch targets from disk"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'save_watch_targets' -Message "app.py must save watch targets to disk"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'check_watch_targets' -Message "app.py must check watch targets during price refresh"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("set_watch_target"\)' -Message "backend must create or update watch targets"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("delete_watch_target"\)' -Message "backend must delete watch targets"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("toggle_watch_target"\)' -Message "backend must toggle watch targets"
Assert-Contains -Path "goldmonitor\socket_alert_configuration.py" -Pattern '@socketio\.on\("reset_watch_target"\)' -Message "backend must reset watch target trigger state"
Assert-Contains -Path "static\alert-rule-editor.js" -Pattern 'kind === ''watch_target''' -Message "unified alert center must render watch target rules"
Assert-Contains -Path "static\alert-log-center.js" -Pattern 'renderNotificationBadges' -Message "alert log must render notification delivery status"
Assert-Contains -Path "goldmonitor\socket_alert_log.py" -Pattern '@socketio\.on\("export_alert_log"\)' -Message "backend must export alert logs"
Assert-Contains -Path "goldmonitor\socket_alert_log.py" -Pattern '@socketio\.on\("clear_alert_log"\)' -Message "backend must clear alert logs"
Assert-Contains -Path "goldmonitor\socket_alert_log.py" -Pattern '@socketio\.on\("update_alert_log_status"\)' -Message "backend must update alert log read state"
Assert-Contains -Path "goldmonitor\socket_alert_log.py" -Pattern '@socketio\.on\("resend_alert_notification"\)' -Message "backend must resend alert notifications"
Assert-NotContains -Path "templates\index.html" -Pattern 'alertLogModeTabs' -Message "frontend must not expose alert log range switching"
Assert-Contains -Path "templates\index.html" -Pattern 'alertLogSearch' -Message "frontend must support alert log search"
Assert-Contains -Path "templates\index.html" -Pattern 'alertUnreadCount' -Message "frontend must show unread alert counts"
Assert-NotContains -Path "templates\index.html" -Pattern 'acknowledgeAlert' -Message "frontend must not expose alert acknowledgement"
Assert-Contains -Path "static\alert-log-center.js" -Pattern 'resendAlertNotification' -Message "frontend must support alert notification resend"
Assert-Contains -Path "templates\index.html" -Pattern 'exportAlertLog' -Message "frontend must expose alert log export"
Assert-Contains -Path "templates\index.html" -Pattern 'clearAlertLog' -Message "frontend must expose alert log clearing"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="threshold-section"' -Message "frontend must not keep the old duplicated threshold form"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="email-switches-section"' -Message "frontend must not keep the old standalone email switch section"
Assert-NotContains -Path "templates\index.html" -Pattern 'class="volatility-section"' -Message "frontend must not keep the old standalone volatility form"
Assert-Contains -Path "templates\index.html" -Pattern 'setFloatingPreset' -Message "settings dialog must expose floating window size presets"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("get_diagnostics"\)' -Message "backend must expose diagnostics export"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("export_config"\)' -Message "backend must expose config backup"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("open_exports_folder"\)' -Message "backend must expose export folder opening"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("import_config"\)' -Message "backend must expose config import"
Assert-Contains -Path "goldmonitor\support_files.py" -Pattern 'schema_version' -Message "config backup must expose a schema version"
Assert-Contains -Path "goldmonitor\support_files.py" -Pattern 'expected_schema_version' -Message "config import preview must expose the supported schema version"
Assert-Contains -Path "goldmonitor\support_files.py" -Pattern 'needs_migration' -Message "config import preview must identify legacy backup migration"
Assert-Contains -Path "goldmonitor\support_files.py" -Pattern 'source_app_version' -Message "config import preview must expose the source app version"
Assert-Contains -Path "static\operations-config.js" -Pattern '旧版备份将在导入时迁移' -Message "config import preview must explain legacy backup migration"
Assert-Contains -Path "static\operations-socket.js" -Pattern 'previewedPayload\s*!==\s*text' -Message "config import confirmation must reject stale preview responses"
Assert-Contains -Path "static\operations-config.js" -Pattern 'ignored\.alert_profiles' -Message "config import preview must include ignored alert profiles"
Assert-Contains -Path "goldmonitor\socket_operations.py" -Pattern '@socketio\.on\("reset_settings"\)' -Message "backend must expose reset settings"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'diagnostic_settings_snapshot' -Message "diagnostics must mask sensitive settings"
Assert-Contains -Path "templates\index.html" -Pattern 'settingsTabOps' -Message "settings dialog must expose operations tab"
Assert-Contains -Path "templates\index.html" -Pattern 'exportDiagnostics' -Message "frontend must export diagnostics"
Assert-Contains -Path "templates\index.html" -Pattern 'openExportsFolder' -Message "frontend must expose export folder opening"
Assert-Contains -Path "templates\index.html" -Pattern 'id="priceRetry"' -Message "index.html must show a manual price retry button"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'socket\.emit\(''refresh_price''' -Message "index.html must request manual price refresh"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'socketClient\.on\(''fetch_status''' -Message "index.html must render fetch status"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'socket\.connect\(\)' -Message "index.html must provide a manual reconnect action"
Assert-Contains -Path "static\app.js" -Pattern 'socket\.on\(''connect_error''' -Message "index.html must explain initial connection failures"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'rate_cached' -Message "index.html must label cached forex rates"
Assert-Contains -Path "static\market-dashboard.js" -Pattern 'gold_cached' -Message "index.html must preserve cached gold status"
Assert-Contains -Path "GoldMonitor.spec" -Pattern 'exclude_binaries=True' -Message "PyInstaller must build in onedir mode"
Assert-Contains -Path "GoldMonitor.spec" -Pattern 'COLLECT\(' -Message "PyInstaller spec must collect files into a distribution directory"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'PrivilegesRequired=lowest' -Message "installer must be per-user"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'dist\\GoldMonitor\\\*' -Message "installer must package the PyInstaller onedir output"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'AppUserModelID:\s*"GoldMonitor\.App"' -Message "installer shortcuts must set the AppUserModelID"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'desktopicon' -Message "installer must support desktop shortcut task"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'CloseApplications=force' -Message "installer must force-close a running app during updates"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'RestartApplications=no' -Message "installer must avoid relying on system restart manager relaunches"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'CloseApplicationsFilter=\{#MyAppExeName\}' -Message "installer must only close the app executable during updates"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'InitializeSetup' -Message "installer must run a pre-install close hook"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'taskkill\.exe' -Message "installer must terminate stale GoldMonitor processes before replacing files"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern '/F /IM \{#MyAppExeName\}' -Message "installer taskkill must target only the app executable"
Assert-NotContains -Path "installer\GoldMonitor.iss" -Pattern '/F /T /IM \{#MyAppExeName\}' -Message "installer must not terminate the updater child process tree"
Assert-Contains -Path "installer\GoldMonitor.iss" -Pattern 'Filename: "\{app\}\\\{#MyAppExeName\}".*Flags: nowait' -Message "installer must launch the app after install and update"
Assert-NotContains -Path "installer\GoldMonitor.iss" -Pattern 'skipifsilent' -Message "silent updates must not skip launching the app after install"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'EVENT_TIMELINE_TYPES' -Message "backend must define supported event timeline types"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_event_timeline_state' -Message "backend must build event timeline state"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_event_timeline_events' -Message "backend must aggregate event timeline events"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'build_review_report' -Message "backend must build deterministic review reports"
Assert-Contains -Path "goldmonitor\application.py" -Pattern 'save_review_report' -Message "backend must save review reports to exports"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("get_event_timeline"\)' -Message "backend must expose event timeline lookup"
Assert-Contains -Path "goldmonitor\socket_history_review.py" -Pattern '@socketio\.on\("export_review_report"\)' -Message "backend must expose review report export"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'event_timeline_updated' -Message "frontend must handle event timeline updates"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'review_report_exported' -Message "frontend must handle review report export results"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'renderEventTimeline' -Message "frontend must render the event timeline"
Assert-Contains -Path "templates\index.html" -Pattern 'exportReviewReport' -Message "frontend must trigger review report export"
Assert-Contains -Path "templates\index.html" -Pattern 'createReviewNoteButton' -Message "event timeline must expose review note creation"
Assert-Contains -Path "templates\index.html" -Pattern 'reviewNoteEditor' -Message "event timeline must expose the review note editor"
Assert-Contains -Path "templates\index.html" -Pattern 'reviewNoteTitle.*maxlength="80"' -Message "review note title input must enforce the backend limit"
Assert-Contains -Path "templates\index.html" -Pattern 'reviewNoteContent.*maxlength="2000"' -Message "review note content input must enforce the backend limit"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'save_review_note' -Message "frontend must submit review note changes"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'delete_review_note' -Message "frontend must request review note deletion"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'review_note_saved' -Message "frontend must handle saved review notes"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'review_note_deleted' -Message "frontend must handle deleted review notes"
Assert-Contains -Path "static\history-review-center.js" -Pattern 'review_notes_updated' -Message "frontend must refresh the timeline after review note changes"

Write-Host "Contract checks passed."
